services:
  - type: web
    name: markaz-loyiha
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ummat_talim.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ummat_talim.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
