# Generated by Django 5.2.4 on 2025-07-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tajriba_yil', models.IntegerField()),
                ('daraja', models.IntegerField(help_text='Daraja qancha yuqori bo`lsa, shuncha yuqoriga chiqadi: ')),
                ('tavsif', models.TextField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ustoz')),
            ],
        ),
    ]
