# Generated by Django 5.2.4 on 2025-07-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloqa',
            name='ism',
            field=models.CharField(default='Anonim', max_length=100),
        ),
    ]
