# Generated by Django 5.2.4 on 2025-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aloqa_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustoz',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='ustoz_rasmlar/'),
        ),
    ]
