# Generated by Django 5.2.4 on 2025-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ustoz_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloqa',
            name='aloqaga_chiqildi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aloqa',
            name='ism',
            field=models.CharField(max_length=100),
        ),
    ]
